DROP TABLE IF EXISTS GroupTab CASCADE;

CREATE TABLE GroupTab (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    leader_id INTEGER NOT NULL,
    open BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (leader_id) REFERENCES User (id)
);